#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jamon-runtime
Version  : 2.4.1
Release  : 1
URL      : https://sourceforge.net/code-snapshots/svn/j/ja/jamon/code/jamon-code-r3129-releases-jamon-runtime-jamon-runtime-2.4.1.zip
Source0  : https://sourceforge.net/code-snapshots/svn/j/ja/jamon/code/jamon-code-r3129-releases-jamon-runtime-jamon-runtime-2.4.1.zip
Source1  : https://repo1.maven.org/maven2/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.jar
Source2  : https://repo1.maven.org/maven2/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MPL-2.0
Requires: mvn-jamon-runtime-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jamon-runtime package.
Group: Data

%description data
data components for the mvn-jamon-runtime package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.jar
/usr/share/java/.m2/repository/org/jamon/jamon-runtime/2.4.1/jamon-runtime-2.4.1.pom
